/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Shadcn colors mapped to CSS variables
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))'
        }
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  safelist: [
    'bg-[#221922]',
    'bg-[#2a587c]',
    'bg-[#472b46]',
    'bg-[#d9d9d9]',
    'bg-[#f0d9b5]',
    'bg-[#f5ebcc]',
    'bg-[rgba(247,246,249,0.1)]',
    'border-[#2a587c]',
    'border-[rgba(255,255,255,0.13)]',
    'border-[transparent]',
    'bottom-[-0.5px]',
    'bottom-[10px]',
    'gap-[15.536px]',
    'gap-[982px]',
    'h-[14px]',
    'h-[15.771px]',
    'h-[163.9%]',
    'h-[177.32%]',
    'h-[2px]',
    'h-[330px]',
    'h-[49.551px]',
    'h-[530px]',
    'h-[700px]',
    'h-[797px]',
    'h-[80px]',
    'h-[8px]',
    'inset-[14.21%_6.25%]',
    'inset-[22.16%_6.25%]',
    'inset-[26.04%_13.54%]',
    'inset-[26.04%_38.54%]',
    'inset-[38.54%_26.04%]',
    'inset-[7.813%]',
    'leading-[1.1]',
    'leading-[1.5]',
    'left-[-44.25%]',
    'left-[28.13%]',
    'left-[37.5%]',
    'left-[4.16%]',
    'max-w-[340px]',
    'max-w-[480px]',
    'min-w-[350px]',
    'min-w-[380px]',
    'mr-[-380px]',
    'p-[15.536px]',
    'pb-[128px]',
    'pl-[64px]',
    'pr-[380px]',
    'pr-[48px]',
    'pt-[64px]',
    'px-[48px]',
    'py-[40px]',
    'right-[20px]',
    'right-[28.13%]',
    'right-[37.5%]',
    'right-[4.17%]',
    'rotate-[180deg]',
    'rotate-[270deg]',
    'rounded-[35.556px]',
    'rounded-[inherit]',
    'scale-y-[-100%]',
    'size-[100px]',
    'size-[18.963px]',
    'size-[21px]',
    'size-[24px]',
    'size-[32px]',
    'size-[40px]',
    'text-[#200102]',
    'text-[#281f26]',
    'text-[#2a587c]',
    'text-[#878787]',
    'text-[#a1141f]',
    'text-[22px]',
    'text-[40px]',
    'top-[-0.24%]',
    'top-[-0.5px]',
    'top-[-35.85%]',
    'tracking-[-1.92px]',
    'tracking-[1.4px]',
    'translate-x-[-50%]',
    'translate-y-[-50%]',
    'w-[1344px]',
    'w-[140px]',
    'w-[144.25%]',
    'w-[1440px]',
    'w-[24px]',
    'w-[469px]',
    'w-[480px]',
    'w-[557px]',
    'w-[827px]',
    'w-[8px]',
    'w-[min-content]'
  ],
  plugins: [require("tailwindcss-animate")],
}
